version: 2
jobs:
  build:
    docker:
    - image: python:3.7.3-stretch
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          python3 -m venv venv
          . venv/bin/activate
          make install
          # Install hadolint
          wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: run lint
        command: ". venv/bin/activate\nmake lint           \n"
    environment:
    - CIRCLE_COMPARE_URL: https://github.com/Jun-depo/dockerproj/compare/707495c43e1b057d4b46a103a2d1fa3202c6cffa...707495c43e1b057d4b46a103a2d1fa3202c6cffa
workflows:
  version: 2
  workflow:
    jobs:
    - build
